---
title: "Prediction"
author: "Kevin Thompson"
date: "August 10, 2019"
output: 
  html_document:
  keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
load("data/.RData")
```


```{r summary, echo=TRUE}

forwardmodel <- lm(SalePrice ~ OverallQual + GrLivArea + Neighborhood, data = housePrices_imputed)
backwardmodel <- lm(SalePrice ~ GarageYrBlt + Exterior2nd + MSSubClass + Exterior1st, data=housePrices_imputed)
backwardmodel$xlevels <- union(backwardmodel$xlevels[["Exterior2nd"]], levels(housePricesTest$Exterior2nd))
stepwisemodel <- lm(SalePrice ~ OverallQual + GrLivArea + Neighborhood, data = housePrices_imputed)
stepwisemodel$xlevels <- union(stepwisemodel$xlevels[["MSSubClass"]], levels(housePricesTest$MSSubClass))
custom <- lm(SalePrice ~ OverallQual + GrLivArea + Neighborhood, data=housePrices_imputed)

resultstable <- data.frame(AjustedR2 = c(Forward = 0.81, Backward = 0.92, Stepwise = 0.86, Custom = 0.81),
                           CVPress = c(Forward = 1.87E12, Backward = 1.63E12, Stepwise = 1.64E12, Custom = 1.89E12),
                           KaggleScore = c(Forward = 0.17697, Backward = 0.62166, Stepwise = 0.26728, Custom = 0.17675),
                           RMSE = c(Foward = 34869, Backward = 22251 , Stepwise = 29145 , Custom = 34529))

forwardpredict <- predict(forwardmodel, newdata = housePricesTest)
backwardpredict <- predict(backwardmodel, newdata = housePricesTest)
stepwisepredict <- predict(stepwisemodel, newdata = housePricesTest)
custompredict <- predict(custom, newdata = housePricesTest)
```


```{r predict, echo=TRUE}
write_csv(data.frame(Id = housePricesTest$Id, SalePrice = forwardpredict), "forwardsubmit.csv")
write_csv(data.frame(Id = housePricesTest$Id, SalePrice = backwardpredict), "backwardsubmit.csv")
write_csv(data.frame(Id = housePricesTest$Id, SalePrice = stepwisepredict), "stepwisesubmit.csv")
write_csv(data.frame(Id = housePricesTest$Id, SalePrice = custompredict), "customsubmit.csv")
```


